services:
  # Backend API (FastAPI)
  - type: web
    name: cinema-api
    runtime: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "8000"

  # Frontend Dashboard (React static site)
  - type: web
    name: cinema-dashboard
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: "https://cinema-1-4p9y.onrender.com"
